### ISSUE TITLE
Update Offstreet on HackRegina tech map

### ISSUE THREAD

**Issue by DJCrossman** [HackRegina/website#2]
**Describe the changes**
Update the technologies and other relevant information for Offsteet

**Location of changes**

[Preview](https://www.hackregina.com/techmap?view=companies&company=offstreet)

<img width="1845" alt="HackRegina Techmap" src="https://github.com/user-attachments/assets/87a5f04b-1faf-489a-a3e1-5b6ff1b4b07b">

**Additional context**
Feel free to review our [Contributing section](https://github.com/HackRegina/website?tab=readme-ov-file#contributing), changes can be made here:
https://github.com/HackRegina/website/blob/main/data/organizations.json#L101-L125

**Comment by DJCrossman** [comment]
@puttputt and @Patrick-Ullrich can you take a look at this.

**Comment by Patrick-Ullrich** [comment]
https://github.com/HackRegina/website/pull/7
